name: build html

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rmd
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: list
        shell: bash -l {0}
        run: conda list
      - name: render
        shell: bash -l {0}
        run: Rscript scripts/render_webpages.R
